# Generated by Django 5.1 on 2024-09-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_adress',
            new_name='delivery_address',
        ),
    ]
